CREATE DATABASE PROJETO_RH;

USE PROJETO_RH;

CREATE TABLE PESSOAS(
	ID BIGINT PRIMARY KEY IDENTITY,
	NOME VARCHAR(300) NOT NULL ,
	DATANASCIMENTO DATE NOT NULL,
	CPF CHAR(11) UNIQUE NOT NULL ,
	RG CHAR(9) UNIQUE NOT NULL,
	TELEFONE CHAR(12) UNIQUE NOT NULL,
	FUNCIONARIO BIT,
);

CREATE TABLE CARGOS(
	ID BIGINT PRIMARY KEY IDENTITY,
	NOME VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE FUNCOES(
	ID BIGINT PRIMARY KEY IDENTITY,
	IDCARGO BIGINT FOREIGN KEY REFERENCES CARGOS(ID) NOT NULL,
	DESCRICAO TEXT NOT NULL,
	CARGAHORARIA TIME NOT NULL,
);

CREATE TABLE FUNCIONARIOS(
	ID BIGINT PRIMARY KEY IDENTITY,
	IDPESSOA BIGINT UNIQUE FOREIGN KEY REFERENCES PESSOAS(ID) NOT NULL,
	IDFUNCAO BIGINT UNIQUE FOREIGN KEY REFERENCES FUNCOES(ID) NOT NULL,
	EMAIL VARCHAR(300) UNIQUE NOT NULL,
	SALARIO MONEY NOT NULL,
	SITUACAO INT NOT NULL
);

CREATE TABLE DEPENDENCIAS(
	ID BIGINT PRIMARY KEY IDENTITY,
	NOME VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE DEPENDENTES(
	ID BIGINT PRIMARY KEY IDENTITY,
	IDPESSOA BIGINT UNIQUE FOREIGN KEY REFERENCES DEPENDENCIAS(ID) NOT NULL,
	IDDEPENDENCIA BIGINT FOREIGN KEY REFERENCES CARGOS(ID) NOT NULL,
	IDFUNCIONARIO  BIGINT UNIQUE FOREIGN KEY REFERENCES FUNCIONARIOS(ID) NOT NULL
);

