CREATE VIEW VerFuncionarios 
AS
SELECT 
F.ID AS 'ID_FUNCIONARIO' , F.EMAIL AS 'EMAIL_FUNCIONARIO', F.SALARIO AS 'SALARIO_FUNCIONARIO',
C.ID AS 'ID_CARGO', C.NOME AS 'CARGO',
FU.ID AS 'ID_FUNCAO' , FU.DESCRICAO AS 'FUNCAO', FU.CARGAHORARIA AS 'CARGA_HORARIA',
P.ID AS 'REGISTRO_FUNCIONARIO' , P.NOME AS 'NOME_FUNCIONARIO',P.TELEFONE AS 'TELEFONE_FUNCIONARIO',P.CPF AS 'CPF_FUNCIONARIO',P.DATANASCIMENTO AS 'DATA_NASCIMENTO_FUNCIONARIO',P.RG AS 'RG_FUNCIONARIO'
FROM FUNCIONARIOS AS F
LEFT JOIN PESSOAS AS P ON IDPESSOA = P.ID
LEFT JOIN FUNCOES AS FU ON F.IDFUNCAO = FU.ID
LEFT JOIN CARGOS AS C ON FU.IDCARGO = C.ID;
GO

CREATE VIEW VerDependentes
AS
SELECT
D.ID AS 'ID_DEPENDENTE',
P.ID AS 'REGISTRO_DEPENDENTE' , P.NOME AS 'NOME_DEPENDENTE',P.TELEFONE AS 'TELEFONE_DEPENDENTE',P.CPF AS 'CPF_DEPENDENTE',P.DATANASCIMENTO AS 'DATA_NASCIMENTO_DEPENDENTE',P.RG AS 'RG_DEPENDENTE',
DP.ID AS 'ID_DEPENDENCIA', DP.NOME AS 'DEPENDENCIA',
F.*
FROM DEPENDENTES AS D
LEFT JOIN PESSOAS AS P ON IDPESSOA = P.ID
LEFT JOIN DEPENDENCIAS AS DP ON IDDEPENDENCIA = DP.ID
LEFT JOIN VerFuncionarios AS F ON IDFUNCIONARIO = F.ID_FUNCIONARIO;
GO

CREATE VIEW VerRegistros
AS
SELECT ID ,NOME,TELEFONE,CPF,DATANASCIMENTO,RG,FUNCIONARIO
FROM PESSOAS;
GO