CREATE VIEW VerFuncoes
AS
SELECT
FUNC.ID AS 'ID_FUNCAO' , FUNC.DESCRICAO AS 'DESCRICAO', FUNC.CARGAHORARIA AS 'CARGA_HORARIA',
C.ID AS 'ID_CARGO' , C.NOME AS 'CARGO'
FROM FUNCOES AS FUNC
LEFT JOIN CARGOS AS C ON FUNC.IDCARGO = C.ID;
GO

CREATE VIEW VerFuncionarios 
AS
SELECT 
F.ID AS 'ID_FUNCIONARIO' , F.EMAIL AS 'EMAIL_FUNCIONARIO', F.SALARIO AS 'SALARIO_FUNCIONARIO',F.SITUACAO AS 'SITUACAO_FUNCIONARIO',
P.ID AS 'REGISTRO_FUNCIONARIO' , P.NOME AS 'NOME_FUNCIONARIO',P.TELEFONE AS 'TELEFONE_FUNCIONARIO',P.CPF AS 'CPF_FUNCIONARIO',P.DATANASCIMENTO AS 'DATA_NASCIMENTO_FUNCIONARIO',P.RG AS 'RG_FUNCIONARIO',
FUNC.*
FROM FUNCIONARIOS AS F
LEFT JOIN PESSOAS AS P ON IDPESSOA = P.ID
LEFT JOIN VerFuncoes AS FUNC ON F.IDFUNCAO = FUNC.ID_FUNCAO;
GO

CREATE VIEW VerDependentes
AS
SELECT
D.ID AS 'ID_DEPENDENTE',
P.ID AS 'REGISTRO_DEPENDENTE' , P.NOME AS 'NOME_DEPENDENTE',P.TELEFONE AS 'TELEFONE_DEPENDENTE',P.CPF AS 'CPF_DEPENDENTE',P.DATANASCIMENTO AS 'DATA_NASCIMENTO_DEPENDENTE',P.RG AS 'RG_DEPENDENTE',
DP.ID AS 'ID_DEPENDENCIA', DP.NOME AS 'DEPENDENCIA',
F.*
FROM DEPENDENTES AS D
LEFT JOIN PESSOAS AS P ON IDPESSOA = P.ID
LEFT JOIN DEPENDENCIAS AS DP ON IDDEPENDENCIA = DP.ID
LEFT JOIN VerFuncionarios AS F ON IDFUNCIONARIO = F.ID_FUNCIONARIO;
GO

CREATE VIEW VerRegistros
AS
SELECT ID ,NOME,TELEFONE,CPF,DATANASCIMENTO,RG,FUNCIONARIO
FROM PESSOAS;
GO
