-- Visualização (Funcionario)
CREATE PROCEDURE VerTodosFuncionarios
AS
BEGIN
SELECT * FROM VerFuncionarios;
END
GO

CREATE PROCEDURE VerFuncionario @ID BIGINT 
AS
BEGIN
SELECT * FROM VerFuncionarios WHERE ID_FUNCIONARIO = @ID;
END
GO

CREATE PROCEDURE VerFuncionarioCpf @CPF CHAR(11) 
AS
BEGIN
SELECT * FROM VerFuncionarios WHERE CPF_FUNCIONARIO = @CPF;
END
GO

CREATE PROCEDURE VerFuncionariosCargo @CARGO BIGINT 
AS
BEGIN
SELECT 
ID_FUNCIONARIO, EMAIL_FUNCIONARIO, SALARIO_FUNCIONARIO,
ID_FUNCAO,FUNCAO,CARGA_HORARIA,
REGISTRO_FUNCIONARIO , NOME_FUNCIONARIO , TELEFONE_FUNCIONARIO, CPF_FUNCIONARIO, DATA_NASCIMENTO_FUNCIONARIO, RG_FUNCIONARIO
FROM VerFuncionarios WHERE CARGO = @CARGO;
END
GO

CREATE PROCEDURE VerFuncionarioSalario @SALARIO_MIN MONEY, @SALARIO_MAX MONEY
AS
BEGIN
SELECT * FROM VerFuncionarios WHERE SALARIO_FUNCIONARIO IN(@SALARIO_MIN,@SALARIO_MAX);
END
GO

-- Visualização (Dependentes)
CREATE PROCEDURE VerTodosDependentes 
AS
BEGIN
SELECT * FROM VerDependentes;
END
GO

CREATE PROCEDURE VerDependente @ID BIGINT 
AS
BEGIN
SELECT * FROM VerDependentes WHERE ID_DEPENDENTE = @ID;
END
GO

CREATE PROCEDURE VerMeusDependente @ID INT 
AS
BEGIN
SELECT * FROM VerDependentes WHERE ID_FUNCIONARIO = @ID;
END
GO

CREATE PROCEDURE VerDependenteCpf @CPF CHAR(11) 
AS
BEGIN
SELECT * FROM VerDependentes WHERE CPF_DEPENDENTE = @CPF;
END
GO

-- Registros
CREATE PROCEDURE VerTodosRegistros
AS
BEGIN
SELECT * FROM VerRegistros;
END
GO

CREATE PROCEDURE VerRegistro @ID BIGINT
AS
BEGIN
SELECT * FROM VerRegistros WHERE ID = @ID;
END
GO

CREATE PROCEDURE VerRegistroPorCpf @CPF CHAR(11) 
AS
BEGIN
SELECT * FROM VerRegistros WHERE CPF = @CPF;
END
GO

-- Tipos Dependencia
CREATE PROCEDURE VerTodasDependencias
AS
BEGIN
SELECT * FROM DEPENDENCIAS;
END
GO

CREATE PROCEDURE VerDependencia @ID BIGINT
AS
BEGIN
SELECT * FROM DEPENDENCIAS WHERE ID = @ID;
END
GO

-- Cargos 

CREATE PROCEDURE VerTodosCargos
AS
BEGIN
SELECT * FROM CARGOS;
END
GO

CREATE PROCEDURE VerCargo @ID BIGINT
AS
BEGIN
SELECT * FROM CARGOS WHERE ID = @ID;
END
GO

-- Funções 

CREATE PROCEDURE VerTodasFuncoes
AS
BEGIN
SELECT * FROM FUNCOES;
END
GO

CREATE PROCEDURE VerFuncao @ID BIGINT
AS
BEGIN
SELECT * FROM FUNCOES WHERE ID = @ID;
END
GO