CREATE PROCEDURE InserirFuncionario 
@NOME VARCHAR(300) , @DATANASCIMENTO DATETIME , @CPF CHAR(11), @RG CHAR(9), @TELEFONE CHAR(12) , 
@IDFUNCAO BIGINT , @EMAIL VARCHAR(300), @SALARIO MONEY , @SITUACAO INT 
AS
BEGIN
INSERT INTO PESSOAS(NOME,DATANASCIMENTO,CPF,RG,TELEFONE,FUNCIONARIO) VALUES(@NOME,@DATANASCIMENTO,@CPF,@RG,@TELEFONE,1);
INSERT INTO FUNCIONARIOS(IDPESSOA,IDFUNCAO,EMAIL,SALARIO,SITUACAO) VALUES(SCOPE_IDENTITY(),@IDFUNCAO,@EMAIL,@SALARIO,@SITUACAO);
END
GO

CREATE PROCEDURE InserirDependente
@NOME VARCHAR(300) , @DATANASCIMENTO DATETIME , @CPF CHAR(11), @RG CHAR(9), @TELEFONE CHAR(12) , 
@IDDEPENDENCIA BIGINT, @IDFUNCIONARIO BIGINT
AS
BEGIN
INSERT INTO PESSOAS(NOME,DATANASCIMENTO,CPF,RG,TELEFONE,FUNCIONARIO) VALUES(@NOME,@DATANASCIMENTO,@CPF,@RG,@TELEFONE,1);
INSERT INTO DEPENDENTES(IDPESSOA,IDDEPENDENCIA,IDFUNCIONARIO) VALUES (SCOPE_IDENTITY(),@IDDEPENDENCIA,@IDFUNCIONARIO);
END
GO

CREATE PROCEDURE InserirFuncao @IDCARGO BIGINT , @DESCRICAO TEXT , @CARGAHORARIA TIME
AS 
BEGIN
INSERT INTO FUNCOES(IDCARGO,DESCRICAO,CARGAHORARIA) VALUES(@IDCARGO,@DESCRICAO,@CARGAHORARIA)
END
GO

CREATE PROCEDURE InserirCargo @NOME VARCHAR(200)
AS 
BEGIN
INSERT INTO CARGOS(NOME) VALUES(@NOME);
END
GO

CREATE PROCEDURE InserirDependencia @NOME VARCHAR(200)
AS 
BEGIN
INSERT INTO DEPENDENCIAS(NOME) VALUES(@NOME);
END
GO